# Generated by Django 5.2.5 on 2025-08-17 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True)),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('genero', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('punt_confianza', models.IntegerField(default=0)),
                ('punt_empatia', models.IntegerField(default=0)),
                ('punt_resiliencia', models.IntegerField(default=0)),
                ('punt_calma', models.IntegerField(default=0)),
                ('categoria_top', models.CharField(blank=True, choices=[('CONF', 'Confianza'), ('EMPA', 'Empatía'), ('RESI', 'Resiliencia'), ('CALM', 'Calma')], max_length=4)),
                ('respuestas', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('CONF', 'Confianza'), ('EMPA', 'Empatía'), ('RESI', 'Resiliencia'), ('CALM', 'Calma')], max_length=4)),
                ('audiencia', models.CharField(choices=[('ALL', 'Todos'), ('M', 'Solo hombres'), ('F', 'Solo mujeres')], default='ALL', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipBelleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True)),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True)),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('peso', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='bienestar.pregunta')),
            ],
        ),
    ]
